FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY fruits/index.html /usr/share/nginx/html/fruits/index.html
COPY vegetables/veggies.html /usr/share/nginx/html/vegetables/veggies.html
EXPOSE 8080
